function evaluateAllResults(dimension,WVMethod,problem_type,set_number, ...
    solution_number,num_vector,reference_point,k,postNumSol,preNumVec)
    seed_number = 32;
    evaluate_result = zeros(1,2,seed_number);
    for seed = 1:seed_number
        % arr = [cosistence,correct]
        arr = evaluate(dimension,solution_number, ...
            problem_type, set_number, num_vector, ...
            seed,reference_point,WVMethod,k,postNumSol,preNumVec);
        if arr == 0
            continue;
        end
        evaluate_result(:,:,seed) = arr;
    end
    file_name = strcat('./Result/evaluate_result_dim_',num2str(dimension), ...
        '_numVec_',num2str(num_vector),'_probtype_',problem_type, ...
        '_numSol_',num2str(solution_number), ...
        '_p=',num2str(preNumVec),'_h=',num2str(postNumSol), ...
        '_',num2str(reference_point),'_',WVMethod,'_k',num2str(k),'.mat');
    save(file_name, "evaluate_result");
end
