vecNumList  = 100*ones(1,9);
preNumVecL  = [5,10,15,20,100,20,20,20,20];
postNumSolL = [2,2, 2, 2, 0,  40,20,16,10];
kList = 1;
M = 3; proType = 'linear_triangular';
CIR = zeros(1,9);
for vecInd = 1:length(vecNumList)
    p = preNumVecL(vecInd);
    h = postNumSolL(vecInd);
    fileName = sprintf(['./Result/evaluate_result_dim_3_numVec_100_probtype', ...
    '_linear_triangular_numSol_100_p=%d_h=%d_1_UNV_k1.mat'],p,h);
    struct = load(fileName);
    data = struct.evaluate_result;
    CIR(1,vecInd) = mean(data(1,2,:));
end
lowBound = floor(min(CIR)*10)/10;
upBound = ceil(max(CIR)*10)/10;
foldName = 'Figure/Figure5'; fileName = 'Fig5';
fileName = sprintf('./%s/%s',foldName,fileName);        
Fig = figure(...
    'Units',           'pixels',...
    'Name',            fileName,...
    'NumberTitle',     'off',...
    'IntegerHandle',   'off', ...
    'Position',       [100,100,1200,500]);
AxesH = axes(...
    'Parent',          Fig,...
    'XGrid',           'on',...
    'YGrid',           'on',...
    'YLim',            [lowBound,upBound],...
    'Xlim',            [1,9],...
    'Visible',         'on',...
    'FontSize',        25,...
    'XTick',           1:9,...
    'YTick',           lowBound:0.1:upBound,...
    'XTickLabel',      {'S1','S2','S3','S4','R2-HVC','S5','S6','S7','S8'});
AxesH.YLabel.String = 'CIR';

hold on;

x = 1:9;
lw = 8; ms = 20;
color = {'k','r','b','r','g','b','w','k'};
lineInd = 1;
plot(x,CIR(1,:),['-',color{1,lineInd},'s'],'MarkerSize',ms,...
    'MarkerEdgeColor',color{lineInd},'MarkerFaceColor',color{lineInd});
    set(gcf, 'renderer', 'painters');
lineInd = 2;
plot(1:4,CIR(1,1:4),['-',color{1,lineInd},'s'],'MarkerSize',ms,...
    'MarkerEdgeColor',color{lineInd},'MarkerFaceColor',color{lineInd});
    set(gcf, 'renderer', 'painters');
lineInd = 3;
plot(6:9,CIR(1,6:9),['-',color{1,lineInd},'s'],'MarkerSize',ms,...
    'MarkerEdgeColor',color{lineInd},'MarkerFaceColor',color{lineInd});
    set(gcf, 'renderer', 'painters');
saveas(Fig,[Fig.Name],'emf');
close all;
